hw1
maltez/angular_school pull request #5
Opened 2018-08-01 19:56 UTC by maggotinaff

2018-08-02 02:44 UTC, maltez requested changes

2018-08-02 02:44 UTC, maltez commented on HomeWork/andrey.skumin/hw1/main.ts
> +const factorial = (n: number): number => n ? n * factorial(n - 1) : 1;
what about negative numbers?

2018-08-02 02:44 UTC, maltez commented on HomeWork/andrey.skumin/hw1/main.ts
> +    let c = a + b;
type of c?

2018-08-02 13:34 UTC, maggotinaff reviewed
fixed

2018-08-07 03:36 UTC, maltez approved these changes

2018-08-07 03:36 UTC, merged